<?php use Numok\Services\{CreatorHub,CreatorRules}; ?>
<div class="ch-plan"><h3>Action queue</h3><?php if(!$p['actions']): ?><p class="ch-muted">No onboarding actions pending.</p><?php endif; ?>
<?php foreach($p['actions'] as $action): ?><p class="ch-muted"><span class="ch-badge"><?= $e($action['audience']) ?></span> <?= $e($action['message']) ?></p><?php endforeach; ?><p class="ch-subtle">Reminders appear inside the portal. No automated DMs or emails are sent.</p></div>
<?php foreach($p['campaigns'] as $campaign): ?><div class="ch-plan"><strong><?= $e($campaign['title']) ?></strong><p class="ch-muted"><?= $e($campaign['status']) ?> · Due <?= $e($campaign['due_at']) ?> UTC · <?= $campaign['progress']['done'] ?>/<?= $campaign['progress']['total'] ?> verified<?= $campaign['overdue']?' · Overdue':'' ?></p><p class="ch-textwrap"><?= $e($campaign['brief']) ?></p></div><?php endforeach; ?>
<?php $reviewRows=\Numok\Database\Database::query('SELECT c.* FROM conversions c JOIN partner_programs pp ON pp.id=c.partner_program_id WHERE pp.partner_id=? ORDER BY c.created_at DESC LIMIT 100',[$p['id']])->fetchAll(); ?>
<details><summary>Review referral payments before a manual payout</summary><p class="ch-muted">Check subscription payments and genuine customers in Stripe. Also inspect suspicious repeats, refunds and disputes. The portal never transfers funds.</p><?php if(!$reviewRows): ?><p>No attributed payment records to review yet.</p><?php else: ?><div class="ch-tablewrap"><table class="ch-table"><thead><tr><th>Customer record</th><th>Invoice</th><th>Amount</th><th>Status</th></tr></thead><tbody><?php foreach($reviewRows as $payment): ?><tr><td><?php if(preg_match('/^cus_[A-Za-z0-9]+$/',$payment['customer_key']??'')): ?><a class="ch-link" target="_blank" rel="noopener noreferrer" href="https://dashboard.stripe.com/customers/<?= $e($payment['customer_key']) ?>">Review customer in Stripe</a><?php else: ?>Identity not available, inspect source record<?php endif; ?></td><td><?= $e($payment['stripe_payment_id']) ?></td><td><?= $e(strtoupper($payment['currency'])) ?> <?= number_format((float)$payment['amount'],2) ?></td><td><?= $e($payment['status']) ?><?php if(!empty(json_decode($payment['metadata']??'{}',true)['paid_refund_requires_review'])): ?><p>Refund after payout, needs review</p><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><a class="ch-link" href="/admin/conversions">Review all payment records</a><?php endif; ?></details>
<?php $joined=CreatorHub::programs((int)$p['id']);if($joined): ?><details><summary>Propose a campaign</summary><form action="/admin/creators/campaign" method="post" class="ch-formgrid"><input type="hidden" name="csrf" value="<?= $e($csrf) ?>"><input type="hidden" name="partner_id" value="<?= (int)$p['id'] ?>">
<div><label>Program<select name="partner_program_id"><?php foreach($joined as $program): ?><option value="<?= (int)$program['id'] ?>"><?= $e($program['name']) ?></option><?php endforeach; ?></select></label></div><div><label>Deadline (UTC)<input type="date" name="due_at" required></label></div>
<div class="wide"><label>Campaign title<input name="title" required maxlength="180" placeholder="Your first Repostit workflow demo"></label></div><div class="wide"><label>Brief and agreed terms<textarea name="brief" required maxlength="5000" rows="4" placeholder="Describe the audience, real workflow to show, disclosure, link placement and agreed expectations. Do not promise automatic payouts."></textarea></label></div>
<?php for($i=0;$i<3;$i++): ?><div class="wide ch-formgrid"><div><label>Platform<select name="platform[]"><?php foreach(CreatorRules::PLATFORMS as $platform): ?><option value="<?= $e($platform) ?>"><?= $e(ucfirst($platform)) ?></option><?php endforeach; ?></select></label></div><div><label>Format<select name="kind[]"><option value="video">Short video</option><option value="story" <?= $i===1?'selected':'' ?>>Story</option><option value="tutorial">Tutorial</option><option value="post">Post</option></select></label></div><div><label>Quantity, 0 skips this row<input type="number" name="count[]" min="0" max="20" value="<?= $i===0?1:0 ?>"></label></div></div><?php endfor; ?>
<div class="wide"><button class="ch-button secondary" type="submit">Save proposal for creator review</button><p class="ch-subtle">This does not grant access, send a message, publish content or transfer money.</p></div></form></details><?php endif; ?>
