<?php use Numok\Services\{CreatorHub,CreatorRules}; ?>
<div class="ch-plan"><h3>Action queue</h3><?php if(!$p['actions']): ?><p class="ch-muted">No onboarding actions pending.</p><?php endif; ?>
<?php foreach($p['actions'] as $action): ?><p class="ch-muted"><span class="ch-badge"><?= $e($action['audience']) ?></span> <?= $e($action['message']) ?></p><?php endforeach; ?><p class="ch-subtle">Reminders appear inside the portal. No automated DMs or emails are sent.</p></div>
<?php foreach($p['campaigns'] as $campaign): ?><div class="ch-plan"><strong><?= $e($campaign['title']) ?></strong><p class="ch-muted"><?= $e($campaign['status']) ?> · Due <?= $e($campaign['due_at']) ?> UTC · <?= $campaign['progress']['done'] ?>/<?= $campaign['progress']['total'] ?> verified<?= $campaign['overdue']?' · Overdue':'' ?></p><p class="ch-textwrap"><?= $e($campaign['brief']) ?></p></div><?php endforeach; ?>
<?php $joined=CreatorHub::programs((int)$p['id']);if($joined): ?><details><summary>Propose a campaign</summary><form action="/admin/creators/campaign" method="post" class="ch-formgrid"><input type="hidden" name="csrf" value="<?= $e($csrf) ?>"><input type="hidden" name="partner_id" value="<?= (int)$p['id'] ?>">
<div><label>Program<select name="partner_program_id"><?php foreach($joined as $program): ?><option value="<?= (int)$program['id'] ?>"><?= $e($program['name']) ?></option><?php endforeach; ?></select></label></div><div><label>Deadline (UTC)<input type="date" name="due_at" required></label></div>
<div class="wide"><label>Campaign title<input name="title" required maxlength="180" placeholder="Your first Repostit workflow demo"></label></div><div class="wide"><label>Brief and agreed terms<textarea name="brief" required maxlength="5000" rows="4" placeholder="Describe the audience, real workflow to show, disclosure, link placement and agreed expectations. Do not promise automatic payouts."></textarea></label></div>
<?php for($i=0;$i<3;$i++): ?><div class="wide ch-formgrid"><div><label>Platform<select name="platform[]"><?php foreach(CreatorRules::PLATFORMS as $platform): ?><option value="<?= $e($platform) ?>"><?= $e(ucfirst($platform)) ?></option><?php endforeach; ?></select></label></div><div><label>Format<select name="kind[]"><option value="video">Short video</option><option value="story" <?= $i===1?'selected':'' ?>>Story</option><option value="tutorial">Tutorial</option><option value="post">Post</option></select></label></div><div><label>Quantity, 0 skips this row<input type="number" name="count[]" min="0" max="20" value="<?= $i===0?1:0 ?>"></label></div></div><?php endfor; ?>
<div class="wide"><button class="ch-button secondary" type="submit">Save proposal for creator review</button><p class="ch-subtle">This does not grant access, send a message, publish content or transfer money.</p></div></form></details><?php endif; ?>
