<?php $e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8'); ?>
<link rel="stylesheet" href="/assets/css/creator-hub.css?v=creator-flow-20261005">
<div class="creator-hub"><div class="ch-top"><div><div class="ch-kicker">PARTNER OPERATIONS</div><h1>From a yes to real customers.</h1><p class="ch-muted">Profiles, account access, promotional content and payouts. Keep each stage visible.</p></div><a class="ch-button secondary" href="/admin/partners">Manage partner accounts</a></div>
<?php foreach(['success','error'] as $notice): if(!empty($_SESSION[$notice])): ?><div class="ch-notice <?= $notice ?>" role="status"><?= $e($_SESSION[$notice]) ?></div><?php unset($_SESSION[$notice]);endif;endforeach; ?>
<?php foreach($partners as $p): $s=$p['summary']; ?>
<section class="ch-card ch-admincard"><div class="ch-row"><div><h2><?= $e($p['contact_name']) ?></h2><p class="ch-muted ch-textwrap"><?= $e($p['company_name']) ?> · <?= $e($p['email']) ?></p></div><a class="ch-button secondary" href="/admin/creators/<?= (int)$p['id'] ?>/preview">Preview creator workspace</a></div>
<div class="ch-adminmeta"><span><?= !empty($p['profile']['firebase_uid'])?'Repostit account linked':'Repostit account not linked' ?></span><span><?= count($p['contents']) ?> content links</span><span><?= count(array_filter($p['contents'],fn($c)=>$c['status']==='verified')) ?> verified promotions</span><span><?= $s['paying_customers'] ?> paying subscribers</span><span>$<?= number_format($s['commission'],2) ?> commission</span></div>
<?php require __DIR__.'/campaigns.php'; ?>
<?php foreach($p['socials'] as $social): ?><p><a class="ch-link" href="<?= $e($social['profile_url']) ?>" target="_blank" rel="noopener noreferrer"><?= $e($social['display_name']) ?> · <?= $e($social['platform']) ?></a> <span class="ch-muted">Creator-supplied profile</span></p><?php endforeach; ?>
<?php foreach($p['profile']['analytics_snapshot']['connections']??[] as $connection): ?><p class="ch-muted"><?= $e($connection['name']) ?> · <?= $e($connection['platform']) ?>, imported from linked Repostit account</p><?php endforeach; ?>
<?php if(!empty($p['profile']['firebase_uid'])): ?><p class="ch-muted">Annual Influencer access: <?= $e($p['profile']['account_snapshot']['influencerExpiresAt']??'Not yet verified') ?>. <a class="ch-link" href="<?= $e(\Numok\Services\PortalEnvironment::appUrl()) ?>/admin?userId=<?= rawurlencode($p['profile']['firebase_uid']) ?>" target="_blank" rel="noopener">Manage in Repostit admin</a></p><?php endif; ?>
<?php if(!empty($p['profile']['firebase_uid'])&&empty($p['profile']['account_snapshot']['influencerExpiresAt'])): ?><div class="ch-plan"><p class="ch-muted">Approve the promised annual Influencer publishing account for <?= $e($p['profile']['repostit_email']) ?>. Billing and Clips credits are not changed.</p><label class="ch-consent"><input type="checkbox" id="grant-consent-<?= (int)$p['id'] ?>">I have approved this creator and confirmed the annual account offer.</label><button class="ch-button secondary small" type="button" data-grant-partner="<?= (int)$p['id'] ?>">Activate annual account with Repostit admin</button></div><?php endif; ?>
<form action="/admin/creators/sync-referrals" method="post"><input type="hidden" name="csrf" value="<?= $e($csrf) ?>"><input type="hidden" name="partner_id" value="<?= (int)$p['id'] ?>"><button class="ch-button secondary small" type="submit">Refresh signup attribution</button></form>
<?php if($p['contents']): ?><div class="ch-tablewrap"><table class="ch-table"><thead><tr><th>Content</th><th>Published URL</th><th>Result</th><th>Review</th></tr></thead><tbody><?php foreach($p['contents'] as $c): ?><tr><td><?= $e($c['title']) ?><p><?= $e($c['platform']) ?> · <?= $e($c['status']) ?></p></td><td><?php if($c['post_url']): ?><a class="ch-link" target="_blank" rel="noopener noreferrer" href="<?= $e($c['post_url']) ?>">Inspect published content</a><?php else: ?>Not submitted<?php endif; ?></td><td><?= $c['clicks'] ?> visits, <?= $c['signups'] ?> signups, <?= $c['customers'] ?> paying customers</td><td><?php if($c['post_url'] && $c['status']!=='verified'): ?><form action="/admin/creators/verify-content" method="post"><input type="hidden" name="csrf" value="<?= $e($csrf) ?>"><input type="hidden" name="content_id" value="<?= (int)$c['id'] ?>"><button class="ch-button small" type="submit">I verified this promotion</button></form><?php else: ?><span class="ch-muted"><?= $c['status']==='verified'?'Verified':'Awaiting URL' ?></span><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
<div class="ch-formgrid"><?php foreach($s['milestones'] as $m): ?><div class="ch-plan"><strong>$<?= number_format($m['amount']) ?> at <?= $m['threshold'] ?> subscribers</strong><p class="ch-muted"><?= $s['paying_customers'] ?> / <?= $m['threshold'] ?> · <?= $e($m['status']) ?>, subject to manual review</p><?php if($m['status']==='earned'): ?><form class="ch-payoutform" action="/admin/creators/record-bonus" method="post"><input type="hidden" name="csrf" value="<?= $e($csrf) ?>"><input type="hidden" name="partner_id" value="<?= (int)$p['id'] ?>"><input type="hidden" name="threshold" value="<?= $m['threshold'] ?>"><label class="ch-consent"><input type="checkbox" name="referrals_reviewed" value="1" required>I reviewed these referrals for genuine customers, self-referrals, refunds and suspicious activity.</label><label for="reference-<?= $p['id'].'-'.$m['threshold'] ?>">Completed bank transfer reference</label><input id="reference-<?= $p['id'].'-'.$m['threshold'] ?>" name="payment_reference" required minlength="3" maxlength="180"><label class="ch-consent"><input type="checkbox" name="wire_confirmed" value="1" required>I have already sent this wire and verified the receipt.</label><button class="ch-button small" type="submit">Record completed transfer</button></form><?php endif; ?></div><?php endforeach; ?></div>
<p class="ch-subtle">Payout recording does not send money. Thresholds use distinct subscribers from verified positive payments, not free accounts, renewals or complimentary plans. Commission amounts shown here are USD only.</p></section>
<?php endforeach; ?><p id="admin-grant-status" class="ch-statusline" role="status"></p></div>
<script type="application/json" id="firebase-public-config"><?= json_encode($firebaseConfig,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script>
<div id="admin-access-controls" data-csrf="<?= $e($csrf) ?>"></div><script type="module" src="/assets/js/creator-admin.js"></script>
